apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: wanderblog-eks-cluster
  region: eu-west-1
  version: "1.35"
  tags:
    owner: krishnadas
    bu: cwg
    project: wanderblog

iam:
  withOIDC: true

vpc:
  id: vpc-008b5b5588c75990c   # your existing VPC ID
  subnets:
    private:
      eu-west-1a-private:
        id: subnet-0b7560fdc76403b47   # your private subnet in ap-south-1a
      eu-west-1b-private:
        id: subnet-0b6225fa3354175dd   # your private subnet in ap-south-1b

managedNodeGroups:
  - name: wanderblog-node-group
    instanceType: t3.medium
    minSize: 2
    desiredCapacity: 2
    maxSize: 4
    volumeSize: 20
    privateNetworking: true

    iam:
      withAddonPolicies:
        autoScaler: true
        certManager: true
        ebs: true
        albIngress: true

    labels:
      lifecycle: ec2-autoscaler
