apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: wanderblog-eks-cluster
  region: ap-south-1
  version: "1.35"
  tags:
    owner: krishnadas
    bu: cwg
    project: wanderblog

iam:
  withOIDC: true

vpc:
  id: vpc-xxxxxxxxxxxxxxxxx   # your existing VPC ID
  subnets:
    private:
      ap-south-1a-private:
        id: subnet-xxxxxxxxxxxxxxxxx   # your private subnet in ap-south-1a
      ap-south-1b-private:
        id: subnet-yyyyyyyyyyyyyyyyy   # your private subnet in ap-south-1b

managedNodeGroups:
  - name: wanderblog-node-group
    instanceType: t3.medium
    minSize: 2
    desiredCapacity: 2
    maxSize: 4
    volumeSize: 20
    privateNetworking: true

    subnets:
      - ap-south-1a-private
      - ap-south-1b-private

    iam:
      withAddonPolicies:
        autoScaler: true
        certManager: true
        ebs: true
        albIngress: true

    labels:
      lifecycle: ec2-autoscaler
