---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-secrets
  namespace: default
spec:
  encryptedData:
    MONGO_URI: AgC/0zV0FR5g+AvskMicJOaItClJ4zD5RrAVBXE3MIEA1tWgVt/PeR5c286sG/MAkoS1YMK7Mn+N4HNa9Xpgl4PYm6AgASjQPEoWrccmV6/qHSlSEzw20rccUuQ1KPzdAYH0g75eGWAkv2U2MVzAa0/wpZN9PWWxY5RQ6Iq1sG7fb/W4CHdEc9khn7hZKJfuZzDedJB7oCV9UqddG41OiNkG70R6Ctsi1LONHLPUDJy5jFzZtykb+2ZuQvpFuYLwuo0xgKRhOH2eKkCBd3g3YaHyWNR6TrIxQotjownlUrFVbk7ts+zxy7iFJ/HmpNdQ7q0oKmavOc5/EFbk2knWI7hQcCFkmfI/wpTtv0NKvr1t2sBvNq1o8MOscHGwV4Zjq9zInzDzJp7mglmqCjkEElYxtYj0KfNPVosaRCJvvYr8nnsNJ6JYgd8RHF1l3LNWTCEfsBFQr6Xnft34p1O7Mj1+8Xi0iFUmihjSMSYLg6Z8IV3oBgX37xjy7dVi+gpjVQuApEs9FIGsd3dxcWiaICjTFwMDzXVfUVGaLSPPAbHNsMWC2bMp94Tljpnh3dtlzUG72z1uMQ674XmTipfZrqQy+WcUctrnHywNWcf6SRO0FGqfFzGleSZGhGnaiQbNJrndu9Syvy5Jgr/5OnE1/mVDoq0Q1J0gN9xiD1+6qCIg6bB4rt5HdxNH7Y9TkYLW3clITPI00GnIOoq4/3ZX9yYY1d8+ZOKLuOjgH/aseYYa4ttHMLaSbUJwHUEUwYGT+B6wAupIppjfoww1xmMdNUI672c1rg==
  template:
    metadata:
      name: backend-secrets
      namespace: default
