---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongo-secrets
  namespace: default
spec:
  encryptedData:
    MONGO_INITDB_ROOT_PASSWORD: AgCFqOZiHtafaF++L9q5ER8FQL1mbkoImD85gn9XinCXR9JJ0UrFdWKvRyMKI6SCWMBXKDZgXNFrr0KuHxBlUGm0OwjxvzOcuYCN3Ws4lVsPywIHsVMgbU6LtThb7/23rBCxrGkuOAJDOs6KQZ8tJeZrjJTGSoa97jh00q2pT3XKRQY9ny6+VzPI0y0hfVgk6dklTrlNlxmyDtjKVPY/6JhWWGSzrXBlVoEPTHqj95rEr+Gw6pdypbWtv2NmWi7GVRMIte7NZ/75vLmIJCOkCN6xGrbOytFStavCHRbmeA9/SjTrT59828CSpHKuVJxa+3XrssbaV1mEHweG7j+HgW5NrmnSWjk/0xWk90Zm5lEbQ1m4XqdL7um7gPHOM10vPuKC3wrpGJhbkmq44evVBq8wZ63f/v00duHg8l/mY8h9v6W/ivYMj8zoBNIaiAkGfvCnnx5uLfW21hHVBUH2vSeVF7tn7FszXzme8J16WfCOPekoOYabVPKiQ1dO7VfvWtoaBfpXnyLyCXu81bP+pNF2jEeFmnCVIDbCszv+VYRCSfPZJw6vZ+8ajfHMWaTKKdfvpkt9dK4w+8SDFw4mTlh24KdVPWkxkf3cbkcoSKJ0PZZr9xt5tAfKOh9Y2vfw5FMfeWP9+QILeJayA0uwkdEr1XCQvZq/ue86C09zHmbVMMRLKzoGJuQJ6GxedeXfhHJ7hl+ClSqexJ8T
    MONGO_INITDB_ROOT_USERNAME: AgC69zouxufQfhzCKook3prRxCh3gezTv8sBeSFmFsOTg0y24pfLZWCC/3ymr0TJzMjOB/0sByxpO7Ys0X1iLAXobk/jdSlO8jq+M/58pJ4rjTm2Sqig2YkXSAODRFC1k57UasP9GIze5TRahxWOoKI9bv8EpatdR2nK7dPZSGMewb3D3ZSi6R2lqZ8ZQ2zcg9S0OvT1SERKoWr9BRqGZZsVqhKkH/uZ3xR/pi2ohh4bH7ffMGMNuv0HJoF5aj0m1GDd+5H4VUjHUMioiMHjwYFThNosvsHvn7xLMk/JjSeclVmaU5q9BzYQXUWufGTc3Ck+6NfF0dxRUv9nFUf0APyxbcmO7H8yua2XU+26nPK2ZXtLxjD/w5+aKR77/sgxWr8MOMK+3wJeERfB7Wzj6GZjZpcBkCv0p191FFBs64i9C+qhdST2VjEAzAVJKMTQbjnPfLWfVyHcCorVTdbccl548DF9MzN9WoExvNLTyI/ywkIZ48xt6LMG9dVQYXyYlDf4VJLrHGG2vOF04OEWXL/eYTGb7UBwNUo7luBi2AQZGPcWJ9UTc+lWuuzuKFe1Cpg1CGpJC1nxI0nSZ23X0p5rxNO8+6dE6LULZe//hcWYjSTidQLFOClDyhNbqRbgi8MriOQUv6+hdcjOANS8OuFJ5zfhsrGG/T0r6DU+L/lZe8xpCbn4THDIbYKASyioN23wbyXO2Q==
  template:
    metadata:
      name: mongo-secrets
      namespace: default
